### PR TITLE
Working for Rails 5.2.0.alpha

### PR DESCRIPTION
**Pull request by Schwad**
I'm working on the Rails 5.2.0.alpha release on an application and tried to use this gem. I was using the foreign keys component. 

It first broke on the (typo?) `:cities` reference so I changed that back to `table`. Then it also could not find `extract_foreign_key_action`, with a stack of:

```
-- extract_foreign_key_action("a")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method 'extract_foreign_key_action' for #<MyMigrationToUuid:0x00007fa31498f828>
```

In Rails core that is a private method, so I explicitly listed it in `schema_helpers`. Then to be safe I also added `require 'webdack/uuid_migration/schema_helpers'` to my migration.

With those changes it worked exactly as described. Figured I might as well supply you with the PR that worked for me as a thank you for all your hard work! :)

### CODE REVIEW

**Comment by Schwad** [comment]
NOTE: On a retest `require 'webdack/uuid_migration/schema_helpers'` wasn't needed, it was just me being paranoid.

**Comment by kum-deepak** [comment]
Many thanks! I will do a review in couple of days and merge it.

I will update README. I will also remove Ruby 1.9.3 from Travis test setup.

**Comment by Schwad** [comment]
Awesome. Thank you so much for creating this gem, it really really helped a
lot with our migration. :)

**Comment by kum-deepak** [comment]
Merged the pull request, updated test cases to work with Rails 5.0 and 5.1, updated Travis to include newer Ruby/Rails, updated README, added your name to contributors, and released a new version 1.1.0.

**Comment by kum-deepak** [comment]
Need help in configuring Travis for Rails 5.2. I was unable to write the Gemfile for Rails5.2.0 alpha.

Please pull the recent changes and see the following files:
- .travis.yml
- gemfiles/rails52.gemfile

It is not a priority, it can wait till Rails 5.2.0 is released.

**Comment by Schwad** [comment]
@kum-deepak thanks, I'll have a look at it and at the very least make sure we're good for 5.2.0 stable this winter.
